# Generated by Django 3.0.5 on 2023-08-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cricketteam',
            old_name='todal_runs',
            new_name='total_runs',
        ),
    ]
